set(_CATKIN_CURRENT_PACKAGE "kautham")
set(kautham_VERSION "3.0.0")
set(kautham_MAINTAINER "Jan Rosell <jan.rosell@upc.edu>")
set(kautham_PACKAGE_FORMAT "1")
set(kautham_BUILD_DEPENDS "roscpp" "std_msgs" "trajectory_msgs")
set(kautham_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "trajectory_msgs")
set(kautham_BUILDTOOL_DEPENDS "catkin")
set(kautham_BUILDTOOL_EXPORT_DEPENDS )
set(kautham_EXEC_DEPENDS "roscpp" "std_msgs" "trajectory_msgs")
set(kautham_RUN_DEPENDS "roscpp" "std_msgs" "trajectory_msgs")
set(kautham_TEST_DEPENDS )
set(kautham_DOC_DEPENDS )
set(kautham_DEPRECATED "")