// Generated by gencpp from file kautham/AddObstacleRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_ADDOBSTACLEREQUEST_H
#define KAUTHAM_MESSAGE_ADDOBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct AddObstacleRequest_
{
  typedef AddObstacleRequest_<ContainerAllocator> Type;

  AddObstacleRequest_()
    : obstacle()
    , scale(0.0)
    , home()  {
    }
  AddObstacleRequest_(const ContainerAllocator& _alloc)
    : obstacle(_alloc)
    , scale(0.0)
    , home(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _obstacle_type;
  _obstacle_type obstacle;

   typedef float _scale_type;
  _scale_type scale;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _home_type;
  _home_type home;




  typedef boost::shared_ptr< ::kautham::AddObstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::AddObstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddObstacleRequest_

typedef ::kautham::AddObstacleRequest_<std::allocator<void> > AddObstacleRequest;

typedef boost::shared_ptr< ::kautham::AddObstacleRequest > AddObstacleRequestPtr;
typedef boost::shared_ptr< ::kautham::AddObstacleRequest const> AddObstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::AddObstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::AddObstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::AddObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::AddObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::AddObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::AddObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::AddObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::AddObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::AddObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5842047c781ca8c7fb165d88d3b2ec7b";
  }

  static const char* value(const ::kautham::AddObstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5842047c781ca8c7ULL;
  static const uint64_t static_value2 = 0xfb165d88d3b2ec7bULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::AddObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/AddObstacleRequest";
  }

  static const char* value(const ::kautham::AddObstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::AddObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obstacle\n\
float32 scale\n\
float32[] home\n\
";
  }

  static const char* value(const ::kautham::AddObstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::AddObstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle);
      stream.next(m.scale);
      stream.next(m.home);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddObstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::AddObstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::AddObstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "obstacle: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.obstacle);
    s << indent << "scale: ";
    Printer<float>::stream(s, indent + "  ", v.scale);
    s << indent << "home[]" << std::endl;
    for (size_t i = 0; i < v.home.size(); ++i)
    {
      s << indent << "  home[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.home[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_ADDOBSTACLEREQUEST_H
