// Generated by gencpp from file kautham/AddRobot.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_ADDROBOT_H
#define KAUTHAM_MESSAGE_ADDROBOT_H

#include <ros/service_traits.h>


#include <kautham/AddRobotRequest.h>
#include <kautham/AddRobotResponse.h>


namespace kautham
{

struct AddRobot
{

typedef AddRobotRequest Request;
typedef AddRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddRobot
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::AddRobot > {
  static const char* value()
  {
    return "cd3e6627dc1126b5a84d0fb3747c15da";
  }

  static const char* value(const ::kautham::AddRobot&) { return value(); }
};

template<>
struct DataType< ::kautham::AddRobot > {
  static const char* value()
  {
    return "kautham/AddRobot";
  }

  static const char* value(const ::kautham::AddRobot&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::AddRobotRequest> should match 
// service_traits::MD5Sum< ::kautham::AddRobot > 
template<>
struct MD5Sum< ::kautham::AddRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::AddRobot >::value();
  }
  static const char* value(const ::kautham::AddRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::AddRobotRequest> should match 
// service_traits::DataType< ::kautham::AddRobot > 
template<>
struct DataType< ::kautham::AddRobotRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::AddRobot >::value();
  }
  static const char* value(const ::kautham::AddRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::AddRobotResponse> should match 
// service_traits::MD5Sum< ::kautham::AddRobot > 
template<>
struct MD5Sum< ::kautham::AddRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::AddRobot >::value();
  }
  static const char* value(const ::kautham::AddRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::AddRobotResponse> should match 
// service_traits::DataType< ::kautham::AddRobot > 
template<>
struct DataType< ::kautham::AddRobotResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::AddRobot >::value();
  }
  static const char* value(const ::kautham::AddRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_ADDROBOT_H
