// Generated by gencpp from file kautham/AttachObstacle2RobotLinkRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_ATTACHOBSTACLE2ROBOTLINKREQUEST_H
#define KAUTHAM_MESSAGE_ATTACHOBSTACLE2ROBOTLINKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct AttachObstacle2RobotLinkRequest_
{
  typedef AttachObstacle2RobotLinkRequest_<ContainerAllocator> Type;

  AttachObstacle2RobotLinkRequest_()
    : robot(0)
    , link(0)
    , obs(0)  {
    }
  AttachObstacle2RobotLinkRequest_(const ContainerAllocator& _alloc)
    : robot(0)
    , link(0)
    , obs(0)  {
  (void)_alloc;
    }



   typedef int64_t _robot_type;
  _robot_type robot;

   typedef int64_t _link_type;
  _link_type link;

   typedef int64_t _obs_type;
  _obs_type obs;




  typedef boost::shared_ptr< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AttachObstacle2RobotLinkRequest_

typedef ::kautham::AttachObstacle2RobotLinkRequest_<std::allocator<void> > AttachObstacle2RobotLinkRequest;

typedef boost::shared_ptr< ::kautham::AttachObstacle2RobotLinkRequest > AttachObstacle2RobotLinkRequestPtr;
typedef boost::shared_ptr< ::kautham::AttachObstacle2RobotLinkRequest const> AttachObstacle2RobotLinkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f4bf766c1991f03044b3d3eab3725b7";
  }

  static const char* value(const ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f4bf766c1991f03ULL;
  static const uint64_t static_value2 = 0x044b3d3eab3725b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/AttachObstacle2RobotLinkRequest";
  }

  static const char* value(const ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 robot\n\
int64 link\n\
int64 obs\n\
";
  }

  static const char* value(const ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
      stream.next(m.link);
      stream.next(m.obs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachObstacle2RobotLinkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::AttachObstacle2RobotLinkRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot);
    s << indent << "link: ";
    Printer<int64_t>::stream(s, indent + "  ", v.link);
    s << indent << "obs: ";
    Printer<int64_t>::stream(s, indent + "  ", v.obs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_ATTACHOBSTACLE2ROBOTLINKREQUEST_H
