// Generated by gencpp from file kautham/AttObj.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_ATTOBJ_H
#define KAUTHAM_MESSAGE_ATTOBJ_H

#include <ros/service_traits.h>


#include <kautham/AttObjRequest.h>
#include <kautham/AttObjResponse.h>


namespace kautham
{

struct AttObj
{

typedef AttObjRequest Request;
typedef AttObjResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttObj
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::AttObj > {
  static const char* value()
  {
    return "9a855f81332331d825acf19b9a7d3200";
  }

  static const char* value(const ::kautham::AttObj&) { return value(); }
};

template<>
struct DataType< ::kautham::AttObj > {
  static const char* value()
  {
    return "kautham/AttObj";
  }

  static const char* value(const ::kautham::AttObj&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::AttObjRequest> should match 
// service_traits::MD5Sum< ::kautham::AttObj > 
template<>
struct MD5Sum< ::kautham::AttObjRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::AttObj >::value();
  }
  static const char* value(const ::kautham::AttObjRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::AttObjRequest> should match 
// service_traits::DataType< ::kautham::AttObj > 
template<>
struct DataType< ::kautham::AttObjRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::AttObj >::value();
  }
  static const char* value(const ::kautham::AttObjRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::AttObjResponse> should match 
// service_traits::MD5Sum< ::kautham::AttObj > 
template<>
struct MD5Sum< ::kautham::AttObjResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::AttObj >::value();
  }
  static const char* value(const ::kautham::AttObjResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::AttObjResponse> should match 
// service_traits::DataType< ::kautham::AttObj > 
template<>
struct DataType< ::kautham::AttObjResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::AttObj >::value();
  }
  static const char* value(const ::kautham::AttObjResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_ATTOBJ_H
