// Generated by gencpp from file kautham/AttObjRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_ATTOBJREQUEST_H
#define KAUTHAM_MESSAGE_ATTOBJREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct AttObjRequest_
{
  typedef AttObjRequest_<ContainerAllocator> Type;

  AttObjRequest_()
    : Robot(0)
    , Obj(0)  {
    }
  AttObjRequest_(const ContainerAllocator& _alloc)
    : Robot(0)
    , Obj(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Robot_type;
  _Robot_type Robot;

   typedef uint8_t _Obj_type;
  _Obj_type Obj;




  typedef boost::shared_ptr< ::kautham::AttObjRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::AttObjRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AttObjRequest_

typedef ::kautham::AttObjRequest_<std::allocator<void> > AttObjRequest;

typedef boost::shared_ptr< ::kautham::AttObjRequest > AttObjRequestPtr;
typedef boost::shared_ptr< ::kautham::AttObjRequest const> AttObjRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::AttObjRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::AttObjRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::AttObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::AttObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::AttObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::AttObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::AttObjRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::AttObjRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::AttObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "291232701ad3ee49b49f74212f6c219f";
  }

  static const char* value(const ::kautham::AttObjRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x291232701ad3ee49ULL;
  static const uint64_t static_value2 = 0xb49f74212f6c219fULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::AttObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/AttObjRequest";
  }

  static const char* value(const ::kautham::AttObjRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::AttObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 Robot\n\
uint8 Obj\n\
";
  }

  static const char* value(const ::kautham::AttObjRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::AttObjRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Robot);
      stream.next(m.Obj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttObjRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::AttObjRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::AttObjRequest_<ContainerAllocator>& v)
  {
    s << indent << "Robot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Robot);
    s << indent << "Obj: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Obj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_ATTOBJREQUEST_H
