// Generated by gencpp from file kautham/CheckCollisionResponse.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_CHECKCOLLISIONRESPONSE_H
#define KAUTHAM_MESSAGE_CHECKCOLLISIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct CheckCollisionResponse_
{
  typedef CheckCollisionResponse_<ContainerAllocator> Type;

  CheckCollisionResponse_()
    : response(false)
    , collisionFree(false)  {
    }
  CheckCollisionResponse_(const ContainerAllocator& _alloc)
    : response(false)
    , collisionFree(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;

   typedef uint8_t _collisionFree_type;
  _collisionFree_type collisionFree;




  typedef boost::shared_ptr< ::kautham::CheckCollisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::CheckCollisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckCollisionResponse_

typedef ::kautham::CheckCollisionResponse_<std::allocator<void> > CheckCollisionResponse;

typedef boost::shared_ptr< ::kautham::CheckCollisionResponse > CheckCollisionResponsePtr;
typedef boost::shared_ptr< ::kautham::CheckCollisionResponse const> CheckCollisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::CheckCollisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::CheckCollisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::CheckCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::CheckCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::CheckCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f0fb100a79777fa56fe95d0bafa3c40";
  }

  static const char* value(const ::kautham::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f0fb100a79777faULL;
  static const uint64_t static_value2 = 0x56fe95d0bafa3c40ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/CheckCollisionResponse";
  }

  static const char* value(const ::kautham::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n\
bool collisionFree\n\
\n\
";
  }

  static const char* value(const ::kautham::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
      stream.next(m.collisionFree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckCollisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::CheckCollisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::CheckCollisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
    s << indent << "collisionFree: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collisionFree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_CHECKCOLLISIONRESPONSE_H
