// Generated by gencpp from file kautham/CheckCollision.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_CHECKCOLLISION_H
#define KAUTHAM_MESSAGE_CHECKCOLLISION_H

#include <ros/service_traits.h>


#include <kautham/CheckCollisionRequest.h>
#include <kautham/CheckCollisionResponse.h>


namespace kautham
{

struct CheckCollision
{

typedef CheckCollisionRequest Request;
typedef CheckCollisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckCollision
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::CheckCollision > {
  static const char* value()
  {
    return "5bd45a4c0c9f595397452675d6ed83a4";
  }

  static const char* value(const ::kautham::CheckCollision&) { return value(); }
};

template<>
struct DataType< ::kautham::CheckCollision > {
  static const char* value()
  {
    return "kautham/CheckCollision";
  }

  static const char* value(const ::kautham::CheckCollision&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::CheckCollisionRequest> should match 
// service_traits::MD5Sum< ::kautham::CheckCollision > 
template<>
struct MD5Sum< ::kautham::CheckCollisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::CheckCollision >::value();
  }
  static const char* value(const ::kautham::CheckCollisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::CheckCollisionRequest> should match 
// service_traits::DataType< ::kautham::CheckCollision > 
template<>
struct DataType< ::kautham::CheckCollisionRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::CheckCollision >::value();
  }
  static const char* value(const ::kautham::CheckCollisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::CheckCollisionResponse> should match 
// service_traits::MD5Sum< ::kautham::CheckCollision > 
template<>
struct MD5Sum< ::kautham::CheckCollisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::CheckCollision >::value();
  }
  static const char* value(const ::kautham::CheckCollisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::CheckCollisionResponse> should match 
// service_traits::DataType< ::kautham::CheckCollision > 
template<>
struct DataType< ::kautham::CheckCollisionResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::CheckCollision >::value();
  }
  static const char* value(const ::kautham::CheckCollisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_CHECKCOLLISION_H
