// Generated by gencpp from file kautham/Connect.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_CONNECT_H
#define KAUTHAM_MESSAGE_CONNECT_H

#include <ros/service_traits.h>


#include <kautham/ConnectRequest.h>
#include <kautham/ConnectResponse.h>


namespace kautham
{

struct Connect
{

typedef ConnectRequest Request;
typedef ConnectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Connect
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::Connect > {
  static const char* value()
  {
    return "e15133a50988a62627c2a009b2a0334f";
  }

  static const char* value(const ::kautham::Connect&) { return value(); }
};

template<>
struct DataType< ::kautham::Connect > {
  static const char* value()
  {
    return "kautham/Connect";
  }

  static const char* value(const ::kautham::Connect&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::ConnectRequest> should match 
// service_traits::MD5Sum< ::kautham::Connect > 
template<>
struct MD5Sum< ::kautham::ConnectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::Connect >::value();
  }
  static const char* value(const ::kautham::ConnectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::ConnectRequest> should match 
// service_traits::DataType< ::kautham::Connect > 
template<>
struct DataType< ::kautham::ConnectRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::Connect >::value();
  }
  static const char* value(const ::kautham::ConnectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::ConnectResponse> should match 
// service_traits::MD5Sum< ::kautham::Connect > 
template<>
struct MD5Sum< ::kautham::ConnectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::Connect >::value();
  }
  static const char* value(const ::kautham::ConnectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::ConnectResponse> should match 
// service_traits::DataType< ::kautham::Connect > 
template<>
struct DataType< ::kautham::ConnectResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::Connect >::value();
  }
  static const char* value(const ::kautham::ConnectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_CONNECT_H
