// Generated by gencpp from file kautham/ConnectRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_CONNECTREQUEST_H
#define KAUTHAM_MESSAGE_CONNECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct ConnectRequest_
{
  typedef ConnectRequest_<ContainerAllocator> Type;

  ConnectRequest_()
    : sample1()
    , sample2()  {
    }
  ConnectRequest_(const ContainerAllocator& _alloc)
    : sample1(_alloc)
    , sample2(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sample1_type;
  _sample1_type sample1;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sample2_type;
  _sample2_type sample2;




  typedef boost::shared_ptr< ::kautham::ConnectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::ConnectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConnectRequest_

typedef ::kautham::ConnectRequest_<std::allocator<void> > ConnectRequest;

typedef boost::shared_ptr< ::kautham::ConnectRequest > ConnectRequestPtr;
typedef boost::shared_ptr< ::kautham::ConnectRequest const> ConnectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::ConnectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::ConnectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ConnectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ConnectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ConnectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ConnectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ConnectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ConnectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::ConnectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38c9513dfbfad4d132c9a48c864f62ba";
  }

  static const char* value(const ::kautham::ConnectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38c9513dfbfad4d1ULL;
  static const uint64_t static_value2 = 0x32c9a48c864f62baULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::ConnectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/ConnectRequest";
  }

  static const char* value(const ::kautham::ConnectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::ConnectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] sample1\n\
float32[] sample2\n\
";
  }

  static const char* value(const ::kautham::ConnectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::ConnectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sample1);
      stream.next(m.sample2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConnectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::ConnectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::ConnectRequest_<ContainerAllocator>& v)
  {
    s << indent << "sample1[]" << std::endl;
    for (size_t i = 0; i < v.sample1.size(); ++i)
    {
      s << indent << "  sample1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sample1[i]);
    }
    s << indent << "sample2[]" << std::endl;
    for (size_t i = 0; i < v.sample2.size(); ++i)
    {
      s << indent << "  sample2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sample2[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_CONNECTREQUEST_H
