// Generated by gencpp from file kautham/DetachObstacleRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_DETACHOBSTACLEREQUEST_H
#define KAUTHAM_MESSAGE_DETACHOBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct DetachObstacleRequest_
{
  typedef DetachObstacleRequest_<ContainerAllocator> Type;

  DetachObstacleRequest_()
    : obs(0)  {
    }
  DetachObstacleRequest_(const ContainerAllocator& _alloc)
    : obs(0)  {
  (void)_alloc;
    }



   typedef int64_t _obs_type;
  _obs_type obs;




  typedef boost::shared_ptr< ::kautham::DetachObstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::DetachObstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetachObstacleRequest_

typedef ::kautham::DetachObstacleRequest_<std::allocator<void> > DetachObstacleRequest;

typedef boost::shared_ptr< ::kautham::DetachObstacleRequest > DetachObstacleRequestPtr;
typedef boost::shared_ptr< ::kautham::DetachObstacleRequest const> DetachObstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::DetachObstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::DetachObstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::DetachObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::DetachObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::DetachObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001678115b32196d81803f47d0ae74e5";
  }

  static const char* value(const ::kautham::DetachObstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001678115b32196dULL;
  static const uint64_t static_value2 = 0x81803f47d0ae74e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/DetachObstacleRequest";
  }

  static const char* value(const ::kautham::DetachObstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 obs\n\
";
  }

  static const char* value(const ::kautham::DetachObstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetachObstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::DetachObstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::DetachObstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "obs: ";
    Printer<int64_t>::stream(s, indent + "  ", v.obs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_DETACHOBSTACLEREQUEST_H
