// Generated by gencpp from file kautham/DetObjRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_DETOBJREQUEST_H
#define KAUTHAM_MESSAGE_DETOBJREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct DetObjRequest_
{
  typedef DetObjRequest_<ContainerAllocator> Type;

  DetObjRequest_()
    : Robot(0)  {
    }
  DetObjRequest_(const ContainerAllocator& _alloc)
    : Robot(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Robot_type;
  _Robot_type Robot;




  typedef boost::shared_ptr< ::kautham::DetObjRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::DetObjRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetObjRequest_

typedef ::kautham::DetObjRequest_<std::allocator<void> > DetObjRequest;

typedef boost::shared_ptr< ::kautham::DetObjRequest > DetObjRequestPtr;
typedef boost::shared_ptr< ::kautham::DetObjRequest const> DetObjRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::DetObjRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::DetObjRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::DetObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::DetObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::DetObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::DetObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::DetObjRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::DetObjRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::DetObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6143baeea981a3bc981604298336955";
  }

  static const char* value(const ::kautham::DetObjRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6143baeea981a3bULL;
  static const uint64_t static_value2 = 0xc981604298336955ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::DetObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/DetObjRequest";
  }

  static const char* value(const ::kautham::DetObjRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::DetObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 Robot\n\
";
  }

  static const char* value(const ::kautham::DetObjRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::DetObjRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetObjRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::DetObjRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::DetObjRequest_<ContainerAllocator>& v)
  {
    s << indent << "Robot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_DETOBJREQUEST_H
