// Generated by gencpp from file kautham/fVector.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_FVECTOR_H
#define KAUTHAM_MESSAGE_FVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct fVector_
{
  typedef fVector_<ContainerAllocator> Type;

  fVector_()
    : v()  {
    }
  fVector_(const ContainerAllocator& _alloc)
    : v(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _v_type;
  _v_type v;




  typedef boost::shared_ptr< ::kautham::fVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::fVector_<ContainerAllocator> const> ConstPtr;

}; // struct fVector_

typedef ::kautham::fVector_<std::allocator<void> > fVector;

typedef boost::shared_ptr< ::kautham::fVector > fVectorPtr;
typedef boost::shared_ptr< ::kautham::fVector const> fVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::fVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::fVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::fVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::fVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::fVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::fVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::fVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::fVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::fVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05b3ad5113715ae3bf7f96db2f38f780";
  }

  static const char* value(const ::kautham::fVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05b3ad5113715ae3ULL;
  static const uint64_t static_value2 = 0xbf7f96db2f38f780ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::fVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/fVector";
  }

  static const char* value(const ::kautham::fVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::fVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] v\n\
\n\
";
  }

  static const char* value(const ::kautham::fVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::fVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::fVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::fVector_<ContainerAllocator>& v)
  {
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_FVECTOR_H
