// Generated by gencpp from file kautham/GetLastPlanComputationTime.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_GETLASTPLANCOMPUTATIONTIME_H
#define KAUTHAM_MESSAGE_GETLASTPLANCOMPUTATIONTIME_H

#include <ros/service_traits.h>


#include <kautham/GetLastPlanComputationTimeRequest.h>
#include <kautham/GetLastPlanComputationTimeResponse.h>


namespace kautham
{

struct GetLastPlanComputationTime
{

typedef GetLastPlanComputationTimeRequest Request;
typedef GetLastPlanComputationTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLastPlanComputationTime
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::GetLastPlanComputationTime > {
  static const char* value()
  {
    return "be5310e7aa4c90cdee120add91648cee";
  }

  static const char* value(const ::kautham::GetLastPlanComputationTime&) { return value(); }
};

template<>
struct DataType< ::kautham::GetLastPlanComputationTime > {
  static const char* value()
  {
    return "kautham/GetLastPlanComputationTime";
  }

  static const char* value(const ::kautham::GetLastPlanComputationTime&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::GetLastPlanComputationTimeRequest> should match 
// service_traits::MD5Sum< ::kautham::GetLastPlanComputationTime > 
template<>
struct MD5Sum< ::kautham::GetLastPlanComputationTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::GetLastPlanComputationTime >::value();
  }
  static const char* value(const ::kautham::GetLastPlanComputationTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::GetLastPlanComputationTimeRequest> should match 
// service_traits::DataType< ::kautham::GetLastPlanComputationTime > 
template<>
struct DataType< ::kautham::GetLastPlanComputationTimeRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::GetLastPlanComputationTime >::value();
  }
  static const char* value(const ::kautham::GetLastPlanComputationTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::GetLastPlanComputationTimeResponse> should match 
// service_traits::MD5Sum< ::kautham::GetLastPlanComputationTime > 
template<>
struct MD5Sum< ::kautham::GetLastPlanComputationTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::GetLastPlanComputationTime >::value();
  }
  static const char* value(const ::kautham::GetLastPlanComputationTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::GetLastPlanComputationTimeResponse> should match 
// service_traits::DataType< ::kautham::GetLastPlanComputationTime > 
template<>
struct DataType< ::kautham::GetLastPlanComputationTimeResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::GetLastPlanComputationTime >::value();
  }
  static const char* value(const ::kautham::GetLastPlanComputationTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_GETLASTPLANCOMPUTATIONTIME_H
