// Generated by gencpp from file kautham/GetNumVertices.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_GETNUMVERTICES_H
#define KAUTHAM_MESSAGE_GETNUMVERTICES_H

#include <ros/service_traits.h>


#include <kautham/GetNumVerticesRequest.h>
#include <kautham/GetNumVerticesResponse.h>


namespace kautham
{

struct GetNumVertices
{

typedef GetNumVerticesRequest Request;
typedef GetNumVerticesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNumVertices
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::GetNumVertices > {
  static const char* value()
  {
    return "54b3c80efd6fae6e6ffff8a4b9facd69";
  }

  static const char* value(const ::kautham::GetNumVertices&) { return value(); }
};

template<>
struct DataType< ::kautham::GetNumVertices > {
  static const char* value()
  {
    return "kautham/GetNumVertices";
  }

  static const char* value(const ::kautham::GetNumVertices&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::GetNumVerticesRequest> should match 
// service_traits::MD5Sum< ::kautham::GetNumVertices > 
template<>
struct MD5Sum< ::kautham::GetNumVerticesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::GetNumVertices >::value();
  }
  static const char* value(const ::kautham::GetNumVerticesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::GetNumVerticesRequest> should match 
// service_traits::DataType< ::kautham::GetNumVertices > 
template<>
struct DataType< ::kautham::GetNumVerticesRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::GetNumVertices >::value();
  }
  static const char* value(const ::kautham::GetNumVerticesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::GetNumVerticesResponse> should match 
// service_traits::MD5Sum< ::kautham::GetNumVertices > 
template<>
struct MD5Sum< ::kautham::GetNumVerticesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::GetNumVertices >::value();
  }
  static const char* value(const ::kautham::GetNumVerticesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::GetNumVerticesResponse> should match 
// service_traits::DataType< ::kautham::GetNumVertices > 
template<>
struct DataType< ::kautham::GetNumVerticesResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::GetNumVertices >::value();
  }
  static const char* value(const ::kautham::GetNumVerticesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_GETNUMVERTICES_H
