// Generated by gencpp from file kautham/GetPath.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_GETPATH_H
#define KAUTHAM_MESSAGE_GETPATH_H

#include <ros/service_traits.h>


#include <kautham/GetPathRequest.h>
#include <kautham/GetPathResponse.h>


namespace kautham
{

struct GetPath
{

typedef GetPathRequest Request;
typedef GetPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPath
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::GetPath > {
  static const char* value()
  {
    return "3eb38c03362ca922ecc4aed737aeab07";
  }

  static const char* value(const ::kautham::GetPath&) { return value(); }
};

template<>
struct DataType< ::kautham::GetPath > {
  static const char* value()
  {
    return "kautham/GetPath";
  }

  static const char* value(const ::kautham::GetPath&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::GetPathRequest> should match 
// service_traits::MD5Sum< ::kautham::GetPath > 
template<>
struct MD5Sum< ::kautham::GetPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::GetPath >::value();
  }
  static const char* value(const ::kautham::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::GetPathRequest> should match 
// service_traits::DataType< ::kautham::GetPath > 
template<>
struct DataType< ::kautham::GetPathRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::GetPath >::value();
  }
  static const char* value(const ::kautham::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::GetPathResponse> should match 
// service_traits::MD5Sum< ::kautham::GetPath > 
template<>
struct MD5Sum< ::kautham::GetPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::GetPath >::value();
  }
  static const char* value(const ::kautham::GetPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::GetPathResponse> should match 
// service_traits::DataType< ::kautham::GetPath > 
template<>
struct DataType< ::kautham::GetPathResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::GetPath >::value();
  }
  static const char* value(const ::kautham::GetPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_GETPATH_H
