// Generated by gencpp from file kautham/MoveRobotsResponse.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_MOVEROBOTSRESPONSE_H
#define KAUTHAM_MESSAGE_MOVEROBOTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct MoveRobotsResponse_
{
  typedef MoveRobotsResponse_<ContainerAllocator> Type;

  MoveRobotsResponse_()
    : Collision(false)  {
    }
  MoveRobotsResponse_(const ContainerAllocator& _alloc)
    : Collision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Collision_type;
  _Collision_type Collision;




  typedef boost::shared_ptr< ::kautham::MoveRobotsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::MoveRobotsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotsResponse_

typedef ::kautham::MoveRobotsResponse_<std::allocator<void> > MoveRobotsResponse;

typedef boost::shared_ptr< ::kautham::MoveRobotsResponse > MoveRobotsResponsePtr;
typedef boost::shared_ptr< ::kautham::MoveRobotsResponse const> MoveRobotsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::MoveRobotsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::MoveRobotsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::MoveRobotsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::MoveRobotsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::MoveRobotsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08035841fd8adb6d99c67de5553f6828";
  }

  static const char* value(const ::kautham::MoveRobotsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08035841fd8adb6dULL;
  static const uint64_t static_value2 = 0x99c67de5553f6828ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/MoveRobotsResponse";
  }

  static const char* value(const ::kautham::MoveRobotsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Collision\n\
";
  }

  static const char* value(const ::kautham::MoveRobotsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::MoveRobotsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::MoveRobotsResponse_<ContainerAllocator>& v)
  {
    s << indent << "Collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_MOVEROBOTSRESPONSE_H
