// Generated by gencpp from file kautham/MoveRobotsRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_MOVEROBOTSREQUEST_H
#define KAUTHAM_MESSAGE_MOVEROBOTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace kautham
{
template <class ContainerAllocator>
struct MoveRobotsRequest_
{
  typedef MoveRobotsRequest_<ContainerAllocator> Type;

  MoveRobotsRequest_()
    : Pose()  {
    }
  MoveRobotsRequest_(const ContainerAllocator& _alloc)
    : Pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _Pose_type;
  _Pose_type Pose;




  typedef boost::shared_ptr< ::kautham::MoveRobotsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::MoveRobotsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotsRequest_

typedef ::kautham::MoveRobotsRequest_<std::allocator<void> > MoveRobotsRequest;

typedef boost::shared_ptr< ::kautham::MoveRobotsRequest > MoveRobotsRequestPtr;
typedef boost::shared_ptr< ::kautham::MoveRobotsRequest const> MoveRobotsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::MoveRobotsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::MoveRobotsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::MoveRobotsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::MoveRobotsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::MoveRobotsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21a5b78cb77256b60e81a1e164a6d550";
  }

  static const char* value(const ::kautham::MoveRobotsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21a5b78cb77256b6ULL;
  static const uint64_t static_value2 = 0x0e81a1e164a6d550ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/MoveRobotsRequest";
  }

  static const char* value(const ::kautham::MoveRobotsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectoryPoint Pose\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
";
  }

  static const char* value(const ::kautham::MoveRobotsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::MoveRobotsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::MoveRobotsRequest_<ContainerAllocator>& v)
  {
    s << indent << "Pose: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.Pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_MOVEROBOTSREQUEST_H
