// Generated by gencpp from file kautham/MoveRobots.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_MOVEROBOTS_H
#define KAUTHAM_MESSAGE_MOVEROBOTS_H

#include <ros/service_traits.h>


#include <kautham/MoveRobotsRequest.h>
#include <kautham/MoveRobotsResponse.h>


namespace kautham
{

struct MoveRobots
{

typedef MoveRobotsRequest Request;
typedef MoveRobotsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRobots
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::MoveRobots > {
  static const char* value()
  {
    return "70db0c1cccc6355b0bdf08387d216ce0";
  }

  static const char* value(const ::kautham::MoveRobots&) { return value(); }
};

template<>
struct DataType< ::kautham::MoveRobots > {
  static const char* value()
  {
    return "kautham/MoveRobots";
  }

  static const char* value(const ::kautham::MoveRobots&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::MoveRobotsRequest> should match 
// service_traits::MD5Sum< ::kautham::MoveRobots > 
template<>
struct MD5Sum< ::kautham::MoveRobotsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::MoveRobots >::value();
  }
  static const char* value(const ::kautham::MoveRobotsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::MoveRobotsRequest> should match 
// service_traits::DataType< ::kautham::MoveRobots > 
template<>
struct DataType< ::kautham::MoveRobotsRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::MoveRobots >::value();
  }
  static const char* value(const ::kautham::MoveRobotsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::MoveRobotsResponse> should match 
// service_traits::MD5Sum< ::kautham::MoveRobots > 
template<>
struct MD5Sum< ::kautham::MoveRobotsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::MoveRobots >::value();
  }
  static const char* value(const ::kautham::MoveRobotsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::MoveRobotsResponse> should match 
// service_traits::DataType< ::kautham::MoveRobots > 
template<>
struct DataType< ::kautham::MoveRobotsResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::MoveRobots >::value();
  }
  static const char* value(const ::kautham::MoveRobotsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_MOVEROBOTS_H
