// Generated by gencpp from file kautham/ProblemOpened.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_PROBLEMOPENED_H
#define KAUTHAM_MESSAGE_PROBLEMOPENED_H

#include <ros/service_traits.h>


#include <kautham/ProblemOpenedRequest.h>
#include <kautham/ProblemOpenedResponse.h>


namespace kautham
{

struct ProblemOpened
{

typedef ProblemOpenedRequest Request;
typedef ProblemOpenedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProblemOpened
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::ProblemOpened > {
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::kautham::ProblemOpened&) { return value(); }
};

template<>
struct DataType< ::kautham::ProblemOpened > {
  static const char* value()
  {
    return "kautham/ProblemOpened";
  }

  static const char* value(const ::kautham::ProblemOpened&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::ProblemOpenedRequest> should match 
// service_traits::MD5Sum< ::kautham::ProblemOpened > 
template<>
struct MD5Sum< ::kautham::ProblemOpenedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::ProblemOpened >::value();
  }
  static const char* value(const ::kautham::ProblemOpenedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::ProblemOpenedRequest> should match 
// service_traits::DataType< ::kautham::ProblemOpened > 
template<>
struct DataType< ::kautham::ProblemOpenedRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::ProblemOpened >::value();
  }
  static const char* value(const ::kautham::ProblemOpenedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::ProblemOpenedResponse> should match 
// service_traits::MD5Sum< ::kautham::ProblemOpened > 
template<>
struct MD5Sum< ::kautham::ProblemOpenedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::ProblemOpened >::value();
  }
  static const char* value(const ::kautham::ProblemOpenedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::ProblemOpenedResponse> should match 
// service_traits::DataType< ::kautham::ProblemOpened > 
template<>
struct DataType< ::kautham::ProblemOpenedResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::ProblemOpened >::value();
  }
  static const char* value(const ::kautham::ProblemOpenedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_PROBLEMOPENED_H
