// Generated by gencpp from file kautham/ProblemSetupResponse.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_PROBLEMSETUPRESPONSE_H
#define KAUTHAM_MESSAGE_PROBLEMSETUPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct ProblemSetupResponse_
{
  typedef ProblemSetupResponse_<ContainerAllocator> Type;

  ProblemSetupResponse_()
    : dim(0)
    , status(false)  {
    }
  ProblemSetupResponse_(const ContainerAllocator& _alloc)
    : dim(0)
    , status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _dim_type;
  _dim_type dim;

   typedef uint8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::kautham::ProblemSetupResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::ProblemSetupResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProblemSetupResponse_

typedef ::kautham::ProblemSetupResponse_<std::allocator<void> > ProblemSetupResponse;

typedef boost::shared_ptr< ::kautham::ProblemSetupResponse > ProblemSetupResponsePtr;
typedef boost::shared_ptr< ::kautham::ProblemSetupResponse const> ProblemSetupResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::ProblemSetupResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::ProblemSetupResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ProblemSetupResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ProblemSetupResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ProblemSetupResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fe75ff6152926cd7d349b63276eced0";
  }

  static const char* value(const ::kautham::ProblemSetupResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fe75ff6152926cdULL;
  static const uint64_t static_value2 = 0x7d349b63276eced0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/ProblemSetupResponse";
  }

  static const char* value(const ::kautham::ProblemSetupResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 dim\n\
bool status\n\
\n\
";
  }

  static const char* value(const ::kautham::ProblemSetupResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dim);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProblemSetupResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::ProblemSetupResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::ProblemSetupResponse_<ContainerAllocator>& v)
  {
    s << indent << "dim: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dim);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_PROBLEMSETUPRESPONSE_H
