// Generated by gencpp from file kautham/RemoveObstacle.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_REMOVEOBSTACLE_H
#define KAUTHAM_MESSAGE_REMOVEOBSTACLE_H

#include <ros/service_traits.h>


#include <kautham/RemoveObstacleRequest.h>
#include <kautham/RemoveObstacleResponse.h>


namespace kautham
{

struct RemoveObstacle
{

typedef RemoveObstacleRequest Request;
typedef RemoveObstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveObstacle
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::RemoveObstacle > {
  static const char* value()
  {
    return "78de84fe6cf9abb719ebadece1aaca39";
  }

  static const char* value(const ::kautham::RemoveObstacle&) { return value(); }
};

template<>
struct DataType< ::kautham::RemoveObstacle > {
  static const char* value()
  {
    return "kautham/RemoveObstacle";
  }

  static const char* value(const ::kautham::RemoveObstacle&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::RemoveObstacleRequest> should match 
// service_traits::MD5Sum< ::kautham::RemoveObstacle > 
template<>
struct MD5Sum< ::kautham::RemoveObstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::RemoveObstacle >::value();
  }
  static const char* value(const ::kautham::RemoveObstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::RemoveObstacleRequest> should match 
// service_traits::DataType< ::kautham::RemoveObstacle > 
template<>
struct DataType< ::kautham::RemoveObstacleRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::RemoveObstacle >::value();
  }
  static const char* value(const ::kautham::RemoveObstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::RemoveObstacleResponse> should match 
// service_traits::MD5Sum< ::kautham::RemoveObstacle > 
template<>
struct MD5Sum< ::kautham::RemoveObstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::RemoveObstacle >::value();
  }
  static const char* value(const ::kautham::RemoveObstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::RemoveObstacleResponse> should match 
// service_traits::DataType< ::kautham::RemoveObstacle > 
template<>
struct DataType< ::kautham::RemoveObstacleResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::RemoveObstacle >::value();
  }
  static const char* value(const ::kautham::RemoveObstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_REMOVEOBSTACLE_H
