// Generated by gencpp from file kautham/RemoveRobot.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_REMOVEROBOT_H
#define KAUTHAM_MESSAGE_REMOVEROBOT_H

#include <ros/service_traits.h>


#include <kautham/RemoveRobotRequest.h>
#include <kautham/RemoveRobotResponse.h>


namespace kautham
{

struct RemoveRobot
{

typedef RemoveRobotRequest Request;
typedef RemoveRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveRobot
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::RemoveRobot > {
  static const char* value()
  {
    return "78de84fe6cf9abb719ebadece1aaca39";
  }

  static const char* value(const ::kautham::RemoveRobot&) { return value(); }
};

template<>
struct DataType< ::kautham::RemoveRobot > {
  static const char* value()
  {
    return "kautham/RemoveRobot";
  }

  static const char* value(const ::kautham::RemoveRobot&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::RemoveRobotRequest> should match 
// service_traits::MD5Sum< ::kautham::RemoveRobot > 
template<>
struct MD5Sum< ::kautham::RemoveRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::RemoveRobot >::value();
  }
  static const char* value(const ::kautham::RemoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::RemoveRobotRequest> should match 
// service_traits::DataType< ::kautham::RemoveRobot > 
template<>
struct DataType< ::kautham::RemoveRobotRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::RemoveRobot >::value();
  }
  static const char* value(const ::kautham::RemoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::RemoveRobotResponse> should match 
// service_traits::MD5Sum< ::kautham::RemoveRobot > 
template<>
struct MD5Sum< ::kautham::RemoveRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::RemoveRobot >::value();
  }
  static const char* value(const ::kautham::RemoveRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::RemoveRobotResponse> should match 
// service_traits::DataType< ::kautham::RemoveRobot > 
template<>
struct DataType< ::kautham::RemoveRobotResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::RemoveRobot >::value();
  }
  static const char* value(const ::kautham::RemoveRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_REMOVEROBOT_H
