// Generated by gencpp from file kautham/ReqCollisionCheckRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_REQCOLLISIONCHECKREQUEST_H
#define KAUTHAM_MESSAGE_REQCOLLISIONCHECKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectoryPoint.h>
#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace kautham
{
template <class ContainerAllocator>
struct ReqCollisionCheckRequest_
{
  typedef ReqCollisionCheckRequest_<ContainerAllocator> Type;

  ReqCollisionCheckRequest_()
    : pose()
    , inactiveRobots(0)
    , inactiveRobotsPose()  {
    }
  ReqCollisionCheckRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , inactiveRobots(0)
    , inactiveRobotsPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _inactiveRobots_type;
  _inactiveRobots_type inactiveRobots;

   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _inactiveRobotsPose_type;
  _inactiveRobotsPose_type inactiveRobotsPose;




  typedef boost::shared_ptr< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReqCollisionCheckRequest_

typedef ::kautham::ReqCollisionCheckRequest_<std::allocator<void> > ReqCollisionCheckRequest;

typedef boost::shared_ptr< ::kautham::ReqCollisionCheckRequest > ReqCollisionCheckRequestPtr;
typedef boost::shared_ptr< ::kautham::ReqCollisionCheckRequest const> ReqCollisionCheckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06594e16e7bd2c90bd63a8141dd9a524";
  }

  static const char* value(const ::kautham::ReqCollisionCheckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06594e16e7bd2c90ULL;
  static const uint64_t static_value2 = 0xbd63a8141dd9a524ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/ReqCollisionCheckRequest";
  }

  static const char* value(const ::kautham::ReqCollisionCheckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectoryPoint pose\n\
uint8 inactiveRobots\n\
trajectory_msgs/JointTrajectoryPoint inactiveRobotsPose\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
";
  }

  static const char* value(const ::kautham::ReqCollisionCheckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.inactiveRobots);
      stream.next(m.inactiveRobotsPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReqCollisionCheckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::ReqCollisionCheckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::ReqCollisionCheckRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "inactiveRobots: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.inactiveRobots);
    s << indent << "inactiveRobotsPose: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.inactiveRobotsPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_REQCOLLISIONCHECKREQUEST_H
