// Generated by gencpp from file kautham/ReqCollisionCheckResponse.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_REQCOLLISIONCHECKRESPONSE_H
#define KAUTHAM_MESSAGE_REQCOLLISIONCHECKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct ReqCollisionCheckResponse_
{
  typedef ReqCollisionCheckResponse_<ContainerAllocator> Type;

  ReqCollisionCheckResponse_()
    : collision(false)  {
    }
  ReqCollisionCheckResponse_(const ContainerAllocator& _alloc)
    : collision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collision_type;
  _collision_type collision;




  typedef boost::shared_ptr< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReqCollisionCheckResponse_

typedef ::kautham::ReqCollisionCheckResponse_<std::allocator<void> > ReqCollisionCheckResponse;

typedef boost::shared_ptr< ::kautham::ReqCollisionCheckResponse > ReqCollisionCheckResponsePtr;
typedef boost::shared_ptr< ::kautham::ReqCollisionCheckResponse const> ReqCollisionCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec9653804a13642f770edbe4a85843b2";
  }

  static const char* value(const ::kautham::ReqCollisionCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec9653804a13642fULL;
  static const uint64_t static_value2 = 0x770edbe4a85843b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/ReqCollisionCheckResponse";
  }

  static const char* value(const ::kautham::ReqCollisionCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool collision\n\
";
  }

  static const char* value(const ::kautham::ReqCollisionCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReqCollisionCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::ReqCollisionCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::ReqCollisionCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_REQCOLLISIONCHECKRESPONSE_H
