// Generated by gencpp from file kautham/ReqPlan.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_REQPLAN_H
#define KAUTHAM_MESSAGE_REQPLAN_H

#include <ros/service_traits.h>


#include <kautham/ReqPlanRequest.h>
#include <kautham/ReqPlanResponse.h>


namespace kautham
{

struct ReqPlan
{

typedef ReqPlanRequest Request;
typedef ReqPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReqPlan
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::ReqPlan > {
  static const char* value()
  {
    return "c28c6945c8dac4a6baf20710ae93dd37";
  }

  static const char* value(const ::kautham::ReqPlan&) { return value(); }
};

template<>
struct DataType< ::kautham::ReqPlan > {
  static const char* value()
  {
    return "kautham/ReqPlan";
  }

  static const char* value(const ::kautham::ReqPlan&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::ReqPlanRequest> should match 
// service_traits::MD5Sum< ::kautham::ReqPlan > 
template<>
struct MD5Sum< ::kautham::ReqPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::ReqPlan >::value();
  }
  static const char* value(const ::kautham::ReqPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::ReqPlanRequest> should match 
// service_traits::DataType< ::kautham::ReqPlan > 
template<>
struct DataType< ::kautham::ReqPlanRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::ReqPlan >::value();
  }
  static const char* value(const ::kautham::ReqPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::ReqPlanResponse> should match 
// service_traits::MD5Sum< ::kautham::ReqPlan > 
template<>
struct MD5Sum< ::kautham::ReqPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::ReqPlan >::value();
  }
  static const char* value(const ::kautham::ReqPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::ReqPlanResponse> should match 
// service_traits::DataType< ::kautham::ReqPlan > 
template<>
struct DataType< ::kautham::ReqPlanResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::ReqPlan >::value();
  }
  static const char* value(const ::kautham::ReqPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_REQPLAN_H
