// Generated by gencpp from file kautham/ReqQueryResponse.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_REQQUERYRESPONSE_H
#define KAUTHAM_MESSAGE_REQQUERYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace kautham
{
template <class ContainerAllocator>
struct ReqQueryResponse_
{
  typedef ReqQueryResponse_<ContainerAllocator> Type;

  ReqQueryResponse_()
    : status(false)
    , plan()
    , obstacles()  {
    }
  ReqQueryResponse_(const ContainerAllocator& _alloc)
    : status(false)
    , plan(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _plan_type;
  _plan_type plan;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _obstacles_type;
  _obstacles_type obstacles;




  typedef boost::shared_ptr< ::kautham::ReqQueryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::ReqQueryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReqQueryResponse_

typedef ::kautham::ReqQueryResponse_<std::allocator<void> > ReqQueryResponse;

typedef boost::shared_ptr< ::kautham::ReqQueryResponse > ReqQueryResponsePtr;
typedef boost::shared_ptr< ::kautham::ReqQueryResponse const> ReqQueryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::ReqQueryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::ReqQueryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ReqQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::ReqQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ReqQueryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::ReqQueryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ReqQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::ReqQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::ReqQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1422ce2fc2df6cd6c8393c45e6a236a";
  }

  static const char* value(const ::kautham::ReqQueryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1422ce2fc2df6cdULL;
  static const uint64_t static_value2 = 0x6c8393c45e6a236aULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::ReqQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/ReqQueryResponse";
  }

  static const char* value(const ::kautham::ReqQueryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::ReqQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n\
trajectory_msgs/JointTrajectory plan\n\
uint32[] obstacles\n\
\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectory\n\
Header header\n\
string[] joint_names\n\
JointTrajectoryPoint[] points\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
";
  }

  static const char* value(const ::kautham::ReqQueryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::ReqQueryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.plan);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReqQueryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::ReqQueryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::ReqQueryResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "plan: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.plan);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_REQQUERYRESPONSE_H
