// Generated by gencpp from file kautham/SaveData.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SAVEDATA_H
#define KAUTHAM_MESSAGE_SAVEDATA_H

#include <ros/service_traits.h>


#include <kautham/SaveDataRequest.h>
#include <kautham/SaveDataResponse.h>


namespace kautham
{

struct SaveData
{

typedef SaveDataRequest Request;
typedef SaveDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveData
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SaveData > {
  static const char* value()
  {
    return "90f671570a831ac11355c7d009fb2e4b";
  }

  static const char* value(const ::kautham::SaveData&) { return value(); }
};

template<>
struct DataType< ::kautham::SaveData > {
  static const char* value()
  {
    return "kautham/SaveData";
  }

  static const char* value(const ::kautham::SaveData&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SaveDataRequest> should match 
// service_traits::MD5Sum< ::kautham::SaveData > 
template<>
struct MD5Sum< ::kautham::SaveDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SaveData >::value();
  }
  static const char* value(const ::kautham::SaveDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SaveDataRequest> should match 
// service_traits::DataType< ::kautham::SaveData > 
template<>
struct DataType< ::kautham::SaveDataRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SaveData >::value();
  }
  static const char* value(const ::kautham::SaveDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SaveDataResponse> should match 
// service_traits::MD5Sum< ::kautham::SaveData > 
template<>
struct MD5Sum< ::kautham::SaveDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SaveData >::value();
  }
  static const char* value(const ::kautham::SaveDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SaveDataResponse> should match 
// service_traits::DataType< ::kautham::SaveData > 
template<>
struct DataType< ::kautham::SaveDataResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SaveData >::value();
  }
  static const char* value(const ::kautham::SaveDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SAVEDATA_H
