// Generated by gencpp from file kautham/SaveDataRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SAVEDATAREQUEST_H
#define KAUTHAM_MESSAGE_SAVEDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace kautham
{
template <class ContainerAllocator>
struct SaveDataRequest_
{
  typedef SaveDataRequest_<ContainerAllocator> Type;

  SaveDataRequest_()
    : problem()  {
    }
  SaveDataRequest_(const ContainerAllocator& _alloc)
    : problem(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _problem_type;
  _problem_type problem;




  typedef boost::shared_ptr< ::kautham::SaveDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SaveDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveDataRequest_

typedef ::kautham::SaveDataRequest_<std::allocator<void> > SaveDataRequest;

typedef boost::shared_ptr< ::kautham::SaveDataRequest > SaveDataRequestPtr;
typedef boost::shared_ptr< ::kautham::SaveDataRequest const> SaveDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SaveDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SaveDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SaveDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SaveDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SaveDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SaveDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SaveDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SaveDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SaveDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb05da14d2435383dc6c819a190caa0e";
  }

  static const char* value(const ::kautham::SaveDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb05da14d2435383ULL;
  static const uint64_t static_value2 = 0xdc6c819a190caa0eULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SaveDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SaveDataRequest";
  }

  static const char* value(const ::kautham::SaveDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SaveDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String problem\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::kautham::SaveDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SaveDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.problem);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SaveDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SaveDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "problem: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.problem);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SAVEDATAREQUEST_H
