// Generated by gencpp from file kautham/SetDefaultRobControls.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETDEFAULTROBCONTROLS_H
#define KAUTHAM_MESSAGE_SETDEFAULTROBCONTROLS_H

#include <ros/service_traits.h>


#include <kautham/SetDefaultRobControlsRequest.h>
#include <kautham/SetDefaultRobControlsResponse.h>


namespace kautham
{

struct SetDefaultRobControls
{

typedef SetDefaultRobControlsRequest Request;
typedef SetDefaultRobControlsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDefaultRobControls
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetDefaultRobControls > {
  static const char* value()
  {
    return "b159fe2f0c57653b71c6e33b23ba4f36";
  }

  static const char* value(const ::kautham::SetDefaultRobControls&) { return value(); }
};

template<>
struct DataType< ::kautham::SetDefaultRobControls > {
  static const char* value()
  {
    return "kautham/SetDefaultRobControls";
  }

  static const char* value(const ::kautham::SetDefaultRobControls&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetDefaultRobControlsRequest> should match 
// service_traits::MD5Sum< ::kautham::SetDefaultRobControls > 
template<>
struct MD5Sum< ::kautham::SetDefaultRobControlsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetDefaultRobControls >::value();
  }
  static const char* value(const ::kautham::SetDefaultRobControlsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetDefaultRobControlsRequest> should match 
// service_traits::DataType< ::kautham::SetDefaultRobControls > 
template<>
struct DataType< ::kautham::SetDefaultRobControlsRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetDefaultRobControls >::value();
  }
  static const char* value(const ::kautham::SetDefaultRobControlsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetDefaultRobControlsResponse> should match 
// service_traits::MD5Sum< ::kautham::SetDefaultRobControls > 
template<>
struct MD5Sum< ::kautham::SetDefaultRobControlsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetDefaultRobControls >::value();
  }
  static const char* value(const ::kautham::SetDefaultRobControlsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetDefaultRobControlsResponse> should match 
// service_traits::DataType< ::kautham::SetDefaultRobControls > 
template<>
struct DataType< ::kautham::SetDefaultRobControlsResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetDefaultRobControls >::value();
  }
  static const char* value(const ::kautham::SetDefaultRobControlsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETDEFAULTROBCONTROLS_H
