// Generated by gencpp from file kautham/SetFixedObsControls.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETFIXEDOBSCONTROLS_H
#define KAUTHAM_MESSAGE_SETFIXEDOBSCONTROLS_H

#include <ros/service_traits.h>


#include <kautham/SetFixedObsControlsRequest.h>
#include <kautham/SetFixedObsControlsResponse.h>


namespace kautham
{

struct SetFixedObsControls
{

typedef SetFixedObsControlsRequest Request;
typedef SetFixedObsControlsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFixedObsControls
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetFixedObsControls > {
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::kautham::SetFixedObsControls&) { return value(); }
};

template<>
struct DataType< ::kautham::SetFixedObsControls > {
  static const char* value()
  {
    return "kautham/SetFixedObsControls";
  }

  static const char* value(const ::kautham::SetFixedObsControls&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetFixedObsControlsRequest> should match 
// service_traits::MD5Sum< ::kautham::SetFixedObsControls > 
template<>
struct MD5Sum< ::kautham::SetFixedObsControlsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetFixedObsControls >::value();
  }
  static const char* value(const ::kautham::SetFixedObsControlsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetFixedObsControlsRequest> should match 
// service_traits::DataType< ::kautham::SetFixedObsControls > 
template<>
struct DataType< ::kautham::SetFixedObsControlsRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetFixedObsControls >::value();
  }
  static const char* value(const ::kautham::SetFixedObsControlsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetFixedObsControlsResponse> should match 
// service_traits::MD5Sum< ::kautham::SetFixedObsControls > 
template<>
struct MD5Sum< ::kautham::SetFixedObsControlsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetFixedObsControls >::value();
  }
  static const char* value(const ::kautham::SetFixedObsControlsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetFixedObsControlsResponse> should match 
// service_traits::DataType< ::kautham::SetFixedObsControls > 
template<>
struct DataType< ::kautham::SetFixedObsControlsResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetFixedObsControls >::value();
  }
  static const char* value(const ::kautham::SetFixedObsControlsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETFIXEDOBSCONTROLS_H
