// Generated by gencpp from file kautham/SetGoal.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETGOAL_H
#define KAUTHAM_MESSAGE_SETGOAL_H

#include <ros/service_traits.h>


#include <kautham/SetGoalRequest.h>
#include <kautham/SetGoalResponse.h>


namespace kautham
{

struct SetGoal
{

typedef SetGoalRequest Request;
typedef SetGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoal
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetGoal > {
  static const char* value()
  {
    return "16f49ae62b5ab7a74082e92a38db2489";
  }

  static const char* value(const ::kautham::SetGoal&) { return value(); }
};

template<>
struct DataType< ::kautham::SetGoal > {
  static const char* value()
  {
    return "kautham/SetGoal";
  }

  static const char* value(const ::kautham::SetGoal&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetGoalRequest> should match 
// service_traits::MD5Sum< ::kautham::SetGoal > 
template<>
struct MD5Sum< ::kautham::SetGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetGoal >::value();
  }
  static const char* value(const ::kautham::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetGoalRequest> should match 
// service_traits::DataType< ::kautham::SetGoal > 
template<>
struct DataType< ::kautham::SetGoalRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetGoal >::value();
  }
  static const char* value(const ::kautham::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetGoalResponse> should match 
// service_traits::MD5Sum< ::kautham::SetGoal > 
template<>
struct MD5Sum< ::kautham::SetGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetGoal >::value();
  }
  static const char* value(const ::kautham::SetGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetGoalResponse> should match 
// service_traits::DataType< ::kautham::SetGoal > 
template<>
struct DataType< ::kautham::SetGoalResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetGoal >::value();
  }
  static const char* value(const ::kautham::SetGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETGOAL_H
