// Generated by gencpp from file kautham/SetInitRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETINITREQUEST_H
#define KAUTHAM_MESSAGE_SETINITREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct SetInitRequest_
{
  typedef SetInitRequest_<ContainerAllocator> Type;

  SetInitRequest_()
    : init()  {
    }
  SetInitRequest_(const ContainerAllocator& _alloc)
    : init(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _init_type;
  _init_type init;




  typedef boost::shared_ptr< ::kautham::SetInitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SetInitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInitRequest_

typedef ::kautham::SetInitRequest_<std::allocator<void> > SetInitRequest;

typedef boost::shared_ptr< ::kautham::SetInitRequest > SetInitRequestPtr;
typedef boost::shared_ptr< ::kautham::SetInitRequest const> SetInitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SetInitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SetInitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetInitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetInitRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetInitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetInitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetInitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetInitRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SetInitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f93ec686a511bdb05f54263193a6ead9";
  }

  static const char* value(const ::kautham::SetInitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf93ec686a511bdb0ULL;
  static const uint64_t static_value2 = 0x5f54263193a6ead9ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SetInitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SetInitRequest";
  }

  static const char* value(const ::kautham::SetInitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SetInitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] init\n\
";
  }

  static const char* value(const ::kautham::SetInitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SetInitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SetInitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SetInitRequest_<ContainerAllocator>& v)
  {
    s << indent << "init[]" << std::endl;
    for (size_t i = 0; i < v.init.size(); ++i)
    {
      s << indent << "  init[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.init[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETINITREQUEST_H
