// Generated by gencpp from file kautham/SetInitObs.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETINITOBS_H
#define KAUTHAM_MESSAGE_SETINITOBS_H

#include <ros/service_traits.h>


#include <kautham/SetInitObsRequest.h>
#include <kautham/SetInitObsResponse.h>


namespace kautham
{

struct SetInitObs
{

typedef SetInitObsRequest Request;
typedef SetInitObsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitObs
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetInitObs > {
  static const char* value()
  {
    return "568a1ace662857bb749c086519c0e1ab";
  }

  static const char* value(const ::kautham::SetInitObs&) { return value(); }
};

template<>
struct DataType< ::kautham::SetInitObs > {
  static const char* value()
  {
    return "kautham/SetInitObs";
  }

  static const char* value(const ::kautham::SetInitObs&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetInitObsRequest> should match 
// service_traits::MD5Sum< ::kautham::SetInitObs > 
template<>
struct MD5Sum< ::kautham::SetInitObsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetInitObs >::value();
  }
  static const char* value(const ::kautham::SetInitObsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetInitObsRequest> should match 
// service_traits::DataType< ::kautham::SetInitObs > 
template<>
struct DataType< ::kautham::SetInitObsRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetInitObs >::value();
  }
  static const char* value(const ::kautham::SetInitObsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetInitObsResponse> should match 
// service_traits::MD5Sum< ::kautham::SetInitObs > 
template<>
struct MD5Sum< ::kautham::SetInitObsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetInitObs >::value();
  }
  static const char* value(const ::kautham::SetInitObsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetInitObsResponse> should match 
// service_traits::DataType< ::kautham::SetInitObs > 
template<>
struct DataType< ::kautham::SetInitObsResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetInitObs >::value();
  }
  static const char* value(const ::kautham::SetInitObsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETINITOBS_H
