// Generated by gencpp from file kautham/SetInitObsRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETINITOBSREQUEST_H
#define KAUTHAM_MESSAGE_SETINITOBSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct SetInitObsRequest_
{
  typedef SetInitObsRequest_<ContainerAllocator> Type;

  SetInitObsRequest_()
    : initObs()  {
    }
  SetInitObsRequest_(const ContainerAllocator& _alloc)
    : initObs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _initObs_type;
  _initObs_type initObs;




  typedef boost::shared_ptr< ::kautham::SetInitObsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SetInitObsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInitObsRequest_

typedef ::kautham::SetInitObsRequest_<std::allocator<void> > SetInitObsRequest;

typedef boost::shared_ptr< ::kautham::SetInitObsRequest > SetInitObsRequestPtr;
typedef boost::shared_ptr< ::kautham::SetInitObsRequest const> SetInitObsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SetInitObsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SetInitObsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetInitObsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetInitObsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetInitObsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetInitObsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetInitObsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetInitObsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SetInitObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1531e61f3b3222743115ad1e9f82ddc0";
  }

  static const char* value(const ::kautham::SetInitObsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1531e61f3b322274ULL;
  static const uint64_t static_value2 = 0x3115ad1e9f82ddc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SetInitObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SetInitObsRequest";
  }

  static const char* value(const ::kautham::SetInitObsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SetInitObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] initObs\n\
";
  }

  static const char* value(const ::kautham::SetInitObsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SetInitObsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.initObs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInitObsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SetInitObsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SetInitObsRequest_<ContainerAllocator>& v)
  {
    s << indent << "initObs[]" << std::endl;
    for (size_t i = 0; i < v.initObs.size(); ++i)
    {
      s << indent << "  initObs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.initObs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETINITOBSREQUEST_H
