// Generated by gencpp from file kautham/SetObsControlsStreamRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETOBSCONTROLSSTREAMREQUEST_H
#define KAUTHAM_MESSAGE_SETOBSCONTROLSSTREAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct SetObsControlsStreamRequest_
{
  typedef SetObsControlsStreamRequest_<ContainerAllocator> Type;

  SetObsControlsStreamRequest_()
    : controls()
    , initObs()  {
    }
  SetObsControlsStreamRequest_(const ContainerAllocator& _alloc)
    : controls(_alloc)
    , initObs(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _controls_type;
  _controls_type controls;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _initObs_type;
  _initObs_type initObs;




  typedef boost::shared_ptr< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetObsControlsStreamRequest_

typedef ::kautham::SetObsControlsStreamRequest_<std::allocator<void> > SetObsControlsStreamRequest;

typedef boost::shared_ptr< ::kautham::SetObsControlsStreamRequest > SetObsControlsStreamRequestPtr;
typedef boost::shared_ptr< ::kautham::SetObsControlsStreamRequest const> SetObsControlsStreamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e89152f7c2231e556e1ec34ae1d0b346";
  }

  static const char* value(const ::kautham::SetObsControlsStreamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe89152f7c2231e55ULL;
  static const uint64_t static_value2 = 0x6e1ec34ae1d0b346ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SetObsControlsStreamRequest";
  }

  static const char* value(const ::kautham::SetObsControlsStreamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string controls\n\
float32[] initObs\n\
";
  }

  static const char* value(const ::kautham::SetObsControlsStreamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controls);
      stream.next(m.initObs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetObsControlsStreamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SetObsControlsStreamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SetObsControlsStreamRequest_<ContainerAllocator>& v)
  {
    s << indent << "controls: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.controls);
    s << indent << "initObs[]" << std::endl;
    for (size_t i = 0; i < v.initObs.size(); ++i)
    {
      s << indent << "  initObs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.initObs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETOBSCONTROLSSTREAMREQUEST_H
