// Generated by gencpp from file kautham/SetObsControls.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETOBSCONTROLS_H
#define KAUTHAM_MESSAGE_SETOBSCONTROLS_H

#include <ros/service_traits.h>


#include <kautham/SetObsControlsRequest.h>
#include <kautham/SetObsControlsResponse.h>


namespace kautham
{

struct SetObsControls
{

typedef SetObsControlsRequest Request;
typedef SetObsControlsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetObsControls
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetObsControls > {
  static const char* value()
  {
    return "3e92b278751cc2f940a8c3b100059169";
  }

  static const char* value(const ::kautham::SetObsControls&) { return value(); }
};

template<>
struct DataType< ::kautham::SetObsControls > {
  static const char* value()
  {
    return "kautham/SetObsControls";
  }

  static const char* value(const ::kautham::SetObsControls&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetObsControlsRequest> should match 
// service_traits::MD5Sum< ::kautham::SetObsControls > 
template<>
struct MD5Sum< ::kautham::SetObsControlsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetObsControls >::value();
  }
  static const char* value(const ::kautham::SetObsControlsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetObsControlsRequest> should match 
// service_traits::DataType< ::kautham::SetObsControls > 
template<>
struct DataType< ::kautham::SetObsControlsRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetObsControls >::value();
  }
  static const char* value(const ::kautham::SetObsControlsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetObsControlsResponse> should match 
// service_traits::MD5Sum< ::kautham::SetObsControls > 
template<>
struct MD5Sum< ::kautham::SetObsControlsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetObsControls >::value();
  }
  static const char* value(const ::kautham::SetObsControlsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetObsControlsResponse> should match 
// service_traits::DataType< ::kautham::SetObsControls > 
template<>
struct DataType< ::kautham::SetObsControlsResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetObsControls >::value();
  }
  static const char* value(const ::kautham::SetObsControlsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETOBSCONTROLS_H
