// Generated by gencpp from file kautham/SetObstaclesConfigRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETOBSTACLESCONFIGREQUEST_H
#define KAUTHAM_MESSAGE_SETOBSTACLESCONFIGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct SetObstaclesConfigRequest_
{
  typedef SetObstaclesConfigRequest_<ContainerAllocator> Type;

  SetObstaclesConfigRequest_()
    : config()  {
    }
  SetObstaclesConfigRequest_(const ContainerAllocator& _alloc)
    : config(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _config_type;
  _config_type config;




  typedef boost::shared_ptr< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetObstaclesConfigRequest_

typedef ::kautham::SetObstaclesConfigRequest_<std::allocator<void> > SetObstaclesConfigRequest;

typedef boost::shared_ptr< ::kautham::SetObstaclesConfigRequest > SetObstaclesConfigRequestPtr;
typedef boost::shared_ptr< ::kautham::SetObstaclesConfigRequest const> SetObstaclesConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e1cb47cc53a4da373482c7cc290f4e1";
  }

  static const char* value(const ::kautham::SetObstaclesConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e1cb47cc53a4da3ULL;
  static const uint64_t static_value2 = 0x73482c7cc290f4e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SetObstaclesConfigRequest";
  }

  static const char* value(const ::kautham::SetObstaclesConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] config\n\
";
  }

  static const char* value(const ::kautham::SetObstaclesConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.config);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetObstaclesConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SetObstaclesConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SetObstaclesConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "config[]" << std::endl;
    for (size_t i = 0; i < v.config.size(); ++i)
    {
      s << indent << "  config[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.config[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETOBSTACLESCONFIGREQUEST_H
