// Generated by gencpp from file kautham/SetPlannerByName.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETPLANNERBYNAME_H
#define KAUTHAM_MESSAGE_SETPLANNERBYNAME_H

#include <ros/service_traits.h>


#include <kautham/SetPlannerByNameRequest.h>
#include <kautham/SetPlannerByNameResponse.h>


namespace kautham
{

struct SetPlannerByName
{

typedef SetPlannerByNameRequest Request;
typedef SetPlannerByNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPlannerByName
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetPlannerByName > {
  static const char* value()
  {
    return "86e89ae99d78051f082ee98c1cba0707";
  }

  static const char* value(const ::kautham::SetPlannerByName&) { return value(); }
};

template<>
struct DataType< ::kautham::SetPlannerByName > {
  static const char* value()
  {
    return "kautham/SetPlannerByName";
  }

  static const char* value(const ::kautham::SetPlannerByName&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetPlannerByNameRequest> should match 
// service_traits::MD5Sum< ::kautham::SetPlannerByName > 
template<>
struct MD5Sum< ::kautham::SetPlannerByNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetPlannerByName >::value();
  }
  static const char* value(const ::kautham::SetPlannerByNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetPlannerByNameRequest> should match 
// service_traits::DataType< ::kautham::SetPlannerByName > 
template<>
struct DataType< ::kautham::SetPlannerByNameRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetPlannerByName >::value();
  }
  static const char* value(const ::kautham::SetPlannerByNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetPlannerByNameResponse> should match 
// service_traits::MD5Sum< ::kautham::SetPlannerByName > 
template<>
struct MD5Sum< ::kautham::SetPlannerByNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetPlannerByName >::value();
  }
  static const char* value(const ::kautham::SetPlannerByNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetPlannerByNameResponse> should match 
// service_traits::DataType< ::kautham::SetPlannerByName > 
template<>
struct DataType< ::kautham::SetPlannerByNameResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetPlannerByName >::value();
  }
  static const char* value(const ::kautham::SetPlannerByNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETPLANNERBYNAME_H
