// Generated by gencpp from file kautham/SetPlannerStream.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETPLANNERSTREAM_H
#define KAUTHAM_MESSAGE_SETPLANNERSTREAM_H

#include <ros/service_traits.h>


#include <kautham/SetPlannerStreamRequest.h>
#include <kautham/SetPlannerStreamResponse.h>


namespace kautham
{

struct SetPlannerStream
{

typedef SetPlannerStreamRequest Request;
typedef SetPlannerStreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPlannerStream
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetPlannerStream > {
  static const char* value()
  {
    return "27e250d0b4007fed97ea34778d6d7442";
  }

  static const char* value(const ::kautham::SetPlannerStream&) { return value(); }
};

template<>
struct DataType< ::kautham::SetPlannerStream > {
  static const char* value()
  {
    return "kautham/SetPlannerStream";
  }

  static const char* value(const ::kautham::SetPlannerStream&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetPlannerStreamRequest> should match 
// service_traits::MD5Sum< ::kautham::SetPlannerStream > 
template<>
struct MD5Sum< ::kautham::SetPlannerStreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetPlannerStream >::value();
  }
  static const char* value(const ::kautham::SetPlannerStreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetPlannerStreamRequest> should match 
// service_traits::DataType< ::kautham::SetPlannerStream > 
template<>
struct DataType< ::kautham::SetPlannerStreamRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetPlannerStream >::value();
  }
  static const char* value(const ::kautham::SetPlannerStreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetPlannerStreamResponse> should match 
// service_traits::MD5Sum< ::kautham::SetPlannerStream > 
template<>
struct MD5Sum< ::kautham::SetPlannerStreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetPlannerStream >::value();
  }
  static const char* value(const ::kautham::SetPlannerStreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetPlannerStreamResponse> should match 
// service_traits::DataType< ::kautham::SetPlannerStream > 
template<>
struct DataType< ::kautham::SetPlannerStreamResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetPlannerStream >::value();
  }
  static const char* value(const ::kautham::SetPlannerStreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETPLANNERSTREAM_H
