// Generated by gencpp from file kautham/SetPlannerRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETPLANNERREQUEST_H
#define KAUTHAM_MESSAGE_SETPLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct SetPlannerRequest_
{
  typedef SetPlannerRequest_<ContainerAllocator> Type;

  SetPlannerRequest_()
    : planner()  {
    }
  SetPlannerRequest_(const ContainerAllocator& _alloc)
    : planner(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _planner_type;
  _planner_type planner;




  typedef boost::shared_ptr< ::kautham::SetPlannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SetPlannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPlannerRequest_

typedef ::kautham::SetPlannerRequest_<std::allocator<void> > SetPlannerRequest;

typedef boost::shared_ptr< ::kautham::SetPlannerRequest > SetPlannerRequestPtr;
typedef boost::shared_ptr< ::kautham::SetPlannerRequest const> SetPlannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SetPlannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SetPlannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetPlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetPlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SetPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20a9edf5c98a0001fcaffdaa7bd2da26";
  }

  static const char* value(const ::kautham::SetPlannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20a9edf5c98a0001ULL;
  static const uint64_t static_value2 = 0xfcaffdaa7bd2da26ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SetPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SetPlannerRequest";
  }

  static const char* value(const ::kautham::SetPlannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SetPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string planner\n\
";
  }

  static const char* value(const ::kautham::SetPlannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SetPlannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.planner);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPlannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SetPlannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SetPlannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "planner: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.planner);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETPLANNERREQUEST_H
