// Generated by gencpp from file kautham/SetRobControlsStream.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETROBCONTROLSSTREAM_H
#define KAUTHAM_MESSAGE_SETROBCONTROLSSTREAM_H

#include <ros/service_traits.h>


#include <kautham/SetRobControlsStreamRequest.h>
#include <kautham/SetRobControlsStreamResponse.h>


namespace kautham
{

struct SetRobControlsStream
{

typedef SetRobControlsStreamRequest Request;
typedef SetRobControlsStreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobControlsStream
} // namespace kautham


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kautham::SetRobControlsStream > {
  static const char* value()
  {
    return "70a7c4a4236b2afb69f24ca18116c470";
  }

  static const char* value(const ::kautham::SetRobControlsStream&) { return value(); }
};

template<>
struct DataType< ::kautham::SetRobControlsStream > {
  static const char* value()
  {
    return "kautham/SetRobControlsStream";
  }

  static const char* value(const ::kautham::SetRobControlsStream&) { return value(); }
};


// service_traits::MD5Sum< ::kautham::SetRobControlsStreamRequest> should match 
// service_traits::MD5Sum< ::kautham::SetRobControlsStream > 
template<>
struct MD5Sum< ::kautham::SetRobControlsStreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetRobControlsStream >::value();
  }
  static const char* value(const ::kautham::SetRobControlsStreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetRobControlsStreamRequest> should match 
// service_traits::DataType< ::kautham::SetRobControlsStream > 
template<>
struct DataType< ::kautham::SetRobControlsStreamRequest>
{
  static const char* value()
  {
    return DataType< ::kautham::SetRobControlsStream >::value();
  }
  static const char* value(const ::kautham::SetRobControlsStreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kautham::SetRobControlsStreamResponse> should match 
// service_traits::MD5Sum< ::kautham::SetRobControlsStream > 
template<>
struct MD5Sum< ::kautham::SetRobControlsStreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kautham::SetRobControlsStream >::value();
  }
  static const char* value(const ::kautham::SetRobControlsStreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kautham::SetRobControlsStreamResponse> should match 
// service_traits::DataType< ::kautham::SetRobControlsStream > 
template<>
struct DataType< ::kautham::SetRobControlsStreamResponse>
{
  static const char* value()
  {
    return DataType< ::kautham::SetRobControlsStream >::value();
  }
  static const char* value(const ::kautham::SetRobControlsStreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETROBCONTROLSSTREAM_H
