// Generated by gencpp from file kautham/SetRobControlsStreamRequest.msg
// DO NOT EDIT!


#ifndef KAUTHAM_MESSAGE_SETROBCONTROLSSTREAMREQUEST_H
#define KAUTHAM_MESSAGE_SETROBCONTROLSSTREAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kautham
{
template <class ContainerAllocator>
struct SetRobControlsStreamRequest_
{
  typedef SetRobControlsStreamRequest_<ContainerAllocator> Type;

  SetRobControlsStreamRequest_()
    : controls()
    , init()
    , goal()  {
    }
  SetRobControlsStreamRequest_(const ContainerAllocator& _alloc)
    : controls(_alloc)
    , init(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _controls_type;
  _controls_type controls;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _init_type;
  _init_type init;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobControlsStreamRequest_

typedef ::kautham::SetRobControlsStreamRequest_<std::allocator<void> > SetRobControlsStreamRequest;

typedef boost::shared_ptr< ::kautham::SetRobControlsStreamRequest > SetRobControlsStreamRequestPtr;
typedef boost::shared_ptr< ::kautham::SetRobControlsStreamRequest const> SetRobControlsStreamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kautham

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb1418a8fef77c80dfd66ebbb00fc56";
  }

  static const char* value(const ::kautham::SetRobControlsStreamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb1418a8fef77c8ULL;
  static const uint64_t static_value2 = 0x0dfd66ebbb00fc56ULL;
};

template<class ContainerAllocator>
struct DataType< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kautham/SetRobControlsStreamRequest";
  }

  static const char* value(const ::kautham::SetRobControlsStreamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string controls\n\
float32[] init\n\
float32[] goal\n\
";
  }

  static const char* value(const ::kautham::SetRobControlsStreamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controls);
      stream.next(m.init);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobControlsStreamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kautham::SetRobControlsStreamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kautham::SetRobControlsStreamRequest_<ContainerAllocator>& v)
  {
    s << indent << "controls: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.controls);
    s << indent << "init[]" << std::endl;
    for (size_t i = 0; i < v.init.size(); ++i)
    {
      s << indent << "  init[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.init[i]);
    }
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAUTHAM_MESSAGE_SETROBCONTROLSSTREAMREQUEST_H
